# Basic Model Structures for RMFB Paper<br/>Part I: CNN Baseline with Visualizations

## Rebuilding All Models with Latest Versions as well as<br/>Doing Learned Visualization of Architecture Structure<sup>\[NB1\]\[NB2\]\[NB3\]</sup><br/>and Especially Grad-CAM<sup>\[NB4\]</sup> Visual Classification Explanations  

David BLACK, GitHub @bballdave025 ,

Working Title for Technical Paper: &quot;AI Computer Vision Methods for
Finding Information-bearing Writing Surfaces (Especially Codex Fragments) Reused in Other Codex Bindings&quot;

Working Title for <em>Fragmentology</em><sup>[NB5]</sup>
(Manuscript Studies) Paper: None Yet

(It would be nice to have some statistics before making a title.)

## Part 1-a: CNN Baseline, Visualizations, GradCAM, all with TensorFlow

#### Why these Notebooks?

There are several reasons for writing these notebooks and doing these various visualizations. The most acceptable (I almost put that in quotation marks; I mean the most-what-employers-or-theoretical-AI/ML-people-would-like-to-hear) answers are: <br/>&nbsp;&nbsp;&nbsp;1) I want to give <strong>greater explainability of the CV model  decisions</strong>,  especially as it relates to the audience of the paper and their acceptance of a non-manual, non-human method, possibly seen as an intruder  into the Manuscript Studies community. I think that if they see the model  making decisions in the same way that <em>they</em> would make decisions, they will be more likely to see it as an aide doing such things as allowing grad students to analyze fragments rather than finding them. For clarity, I mention that the audience consists of the readers of the Binding-Fragment paper to be submitted to <em>Fragmentology</em>; <br/>&nbsp;&nbsp;&nbsp;2) I want to make better decisions as to which model will most-likely make the <strong>goal of ~95% precision and ~70% recall possible on a wide variety of writing-material and binding images</strong>. The ultimate goal for (this stage of) the study is to run the algorithm over as many of FamilySearch's earliest-to-18th Century images (let's make it readable: images from the earliest records they have up to the 1700s) as possible. Through the analysis and visualization of how well the chosen model or models performs, we can have higher confidence that an eventual <strong>one run</strong> over what I'll estimate as 0.5 to 1 billion images with a thoroughly tested and understood/explainable model will <strong>suffice for at least a decade</strong>. <br/>&nbsp;&nbsp;&nbsp;3) (This is a long one.) Especially with the Grad-CAM visualizations of the salient features for model decisions, I want to have something to <strong>show to the Manuscript Studies/Fragmentology community that will get them excited</strong> about <em>helping us</em> to <em>create better training sets</em> and to <em>help create new training sets for interesting phenomena/occurences</em> (for lack of a better word describing what each of the classifications describes). I think that the best example of this is to create a model (or add to the existing model) the search for images that not only have iron-gall-ink damage to the point of going through the page (something I have tried to do without expertise), but which are at different stages<sup>\[NB5\]</sup> of the iron-gall-ink (and other corrosive dye) damage process. I'm also going to face the fact that, even as concerns the main object of study—fragments found in bindings—I'm perhaps passingly knowledgeable but by no means an expert. Seeing heat maps describing what the model thinks is most important in finding a specific images I've classified should make this a more interesting invitation, as it allows quick view of the types of phenomena such models can find in and on writing materials, bindings, etc.

For my estimate of the sum total of such documents, I make reference to the <em>Company Facts</em> page on FamilySearch [as I see it now (archived with numbers updated 2025-04-07)](https://web.archive.org/web/20250423044740/https://www.familysearch.org/en/newsroom/company-facts), which reports "5.65 Billion \[Digital Images Published\]" . For a second opinion, I've looked at the running counter of images digitized at https://www.familysearch.org/en/records/images/, which is at \[let me go take a screenshot\]

<br/>
<div>
  <img src="https://raw.githubusercontent.com/bballdave025/rib-wrist-in-bin-din/refs/heads/main/FamilySearch_5667347462_5point667-B_Images_2025-04-22T113500-0600.png"
       alt="Screenshot of family search dot org forward slash E N forward slash records forward slash images. Tab name is. QUOTE. Explore Historical Images. END QUOTE. Visible text is. QUOTE. Access billions of documents newline FamilySearch has been collecting historical documents since eighteen ninety four and currently has. Left square bracket. Transcriber's note colon. Number in short scale, i.e. without milliard, billiard, et cetera, so ten to the ninth is read billion, ten to the twelfth is read trillion, et cetera. Right bracket. five billion six hundred sixty-seven million, three hundred forty-seven thousand four hundred sixty-one images from all over the world. That makes FamilySearch one of the world's largest collections of historical documents exclamation point. END QUOTE. Bottom toolbar shows eleven colon thirty-five A M. and. four slash twenty-two forward slash two thousand twenty-five. Left Bracket. Date format is as in the stupid U S A format comma month slash day slash year. Right Bracket. An errow points from the annotated text. QUOTE. M D T. Left parenthesis. G M T minus six Right parenthesis. END QUOTE. to the time and date."
       width="500px">
</div>
<br/>

5,667,347,461 (five billion six hundred sixty-seven million, three hundred forty-seven thousand four hundred sixty-one) images. The type of binding we're seeking is most-commonly found in Western and Central Europe going into Russia and Persia, with some around the Mediterranean—including Muslim and Jewish records—the Near East, and the Americas—mostly (Catholic) South America. Since I think that records from the current United States of America probably take up at least a third of all digital images published, and Western/Central Europe <em>at least</em> one quarter of the remaining digital images, my guess is that a search in those geographical regions from the earliest date for which FamilySearch has records to 1799 will yield approximately<br/>$ \frac{2}{3} \cdot \frac{1}{4} \cdot 5.66 \times 10^{9} $ images or $ 9.45 \times 10^{8} \left(\substack{+9e8 \\ -5e9} \: \mathrm{systematic}\right) \left(\pm 0.25e9 \;  \mathrm{who} \! \cdot \! \mathrm{knows}\right) $,<br/>$ \frac{1}{6}\;\mathrm{ish} $ of the records, 500 million to 1.5 billion (again, very $ \mathrm{ish} $).<br/>(Note that my methodology will let in records from the 1800s and even a few from the 1900s, but not on purpose.)

The current study will include around hundreds of thousands of images, with an approximate guess of half being from FamilySearch, for the intial study and publication in <em>Fragmentology</em>. This study entails at least thousands of images, up to tens of thousands, for the training, validation, and test sets. (That is, tens of thousands of images split into the three sets.)

### Some Visualization Ruminations

#### New

I'm going to try using the network architecture visualization tools:

#### [Netron (non-GitHub site)](https://netron.app/)

https://github.com/lutzroeder/netron?tab=readme-ov-file

<strike>https://github.com/lutzroeder/netron/releases/tag/v8.3.9 (has downloads)</strike>

Luckily, we don't have to worry about OS package manager downloads here on SageMaker, 
because we can do the following, according to the README

> `pip install netron`, then run `netron [FILE]` or `netron.start('[FILE]')`

<hr/>

<strong>AS WELL AS</strong> the architecture and convolution result visualization tool, 

<hr/>

#### [Quiver](https://github.com/keplr-io/quiver)

https://github.com/keplr-io/quiver

```
misc{bianquiver,
  title={Quiver},
  author={Bian, Jake},
  year={2016},
  publisher={GitHub},
  howpublished={\url{https://github.com/keplr-io/quiver}},
}
```

Luckily, it's easily installed with

`pip install quiver_engine`

and used as

```
# really quickly

# Build your model in Keras
model = Model(...)

quiver_engine.server.launch(model, classes=['cat','dog'], input_folder='./imgs')
```

More deeply:

> <strong>Usage</strong>
>
> Take your keras `model`, launching Quiver is a one-liner.
> ```
> from quiver_engine import server
> server.launch(model)
> ```
>
> This will launch the visualization at `localhost:5000`
>
> <strong>Options</strong>
>
> ```
>    server.launch(
>        model, # a Keras Model
>
>        classes, # list of output classes from the model to present (if not specified 1000 ImageNet classes will be used)
>
>        top, # number of top predictions to show in the gui (default 5)
>
>        # where to store temporary files generatedby quiver (e.g. image files of layers)
>        temp_folder='./tmp',
>
>        # a folder where input images are stored
>        input_folder='./',
>
>        # the localhost port the dashboard is to be served on
>        port=5000,
>        # custom data mean
>        mean=[123.568, 124.89, 111.56],
>        # custom data standard deviation
>        std=[52.85, 48.65, 51.56]
>    )
> ```

<hr/>

Oh, looks like Quiver is just for Keras. Well, with PyTorch, I can look at

#### [TorchLens](https://github.com/johnmarktaylor91/torchlens)

https://github.com/johnmarktaylor91/torchlens

[On PyPI](https://pypi.org/project/torchlens/) (so from `pip`)

[TorchLens (Nature article HTML)](https://www.nature.com/articles/s41598-023-40807-0)

[TorchLens (Nature article pdf download](https://www.nature.com/articles/s41598-023-40807-0.pdf)

[NIH National Library of Medicine](https://pubmed.ncbi.nlm.nih.gov/36993311/)

<hr/>

Note that a really nice option &ndash; deepvis &ndash; is mentioned by the Quiver author
as an inspiration, but is only available with Caffe.

https://github.com/yosinski/deep-visualization-toolbox

#### Attempted before - and things worked

`model.summary()` and I think there was some kind of `print(model)`

Then

```
model_arch_str = str(model)

with open("this_model_architecture.txt", 'w', encoding='utf-8') as fh:
    fh.write(model_arch_str)
##endof:  with open ... fh
```

Also

`visualkeras`

### Most Important Visualization, GradCAM, for Explainability

[Paper on arXiv](https://arxiv.org/abs/1610.02391) - Landing Page

[Download PDF from arXiv](https://arxiv.org/pdf/1610.02391)

<hr/>

#### For TensorFlow

##### By Keras

This first one might be for `tensorflow<2`

https://keras.io/examples/vision/grad_cam/

##### By @ismailuddin

The following is specifically for TensorFlow2. And it's WONDERFUL! Great, accessible math.

https://github.com/ismailuddin/gradcam-tensorflow-2

He also references @jacobgil

```
$ type atree
atree is aliased to `tree --charset=ascii'

$ atree gradcam-tensorflow-2
gradcam-tensorflow-2
|-- README.md
|-- data
|   |-- cat.jpg
|   |-- cat_and_dog.jpg
|   `-- example.jpg
|-- notebooks
|   `-- GradCam.ipynb
`-- requirements.txt

2 directories, 6 files

$
```


##### By PyImageSearch

And, of course, here's my good, marketing-happy buddy, Adrian Rosebrock

https://pyimagesearch.com/2020/03/09/grad-cam-visualize-class-activation-maps-with-keras-tensorflow-and-deep-learning/

<hr/>

#### For the PyTorch models

##### By @jacobgil

https://github.com/jacobgil/pytorch-grad-cam

```
@misc{jacobgilpytorchcam,
  title={PyTorch library for CAM methods},
  author={Jacob Gildenblat and contributors},
  year={2021},
  publisher={GitHub},
  howpublished={\url{https://github.com/jacobgil/pytorch-grad-cam}},
}
```

This @jacobgil stuff has lots of good references

> https://arxiv.org/abs/1610.02391<br/>
> `Grad-CAM: Visual Explanations from Deep Networks via Gradient-based Localization Ramprasaath R. Selvaraju, Michael Cogswell, Abhishek Das, Ramakrishna Vedantam, Devi Parikh, Dhruv Batra`
>
> https://arxiv.org/abs/2011.08891<br/>
> `Use HiResCAM instead of Grad-CAM for faithful explanations of convolutional neural networks Rachel L. Draelos, Lawrence Carin`
>
> https://arxiv.org/abs/1710.11063<br/>
> `Grad-CAM++: Improved Visual Explanations for Deep Convolutional Networks Aditya Chattopadhyay, Anirban Sarkar, Prantik Howlader, Vineeth N Balasubramanian`
>
> https://arxiv.org/abs/1910.01279<br/>
> `Score-CAM: Score-Weighted Visual Explanations for Convolutional Neural Networks Haofan Wang, Zifan Wang, Mengnan Du, Fan Yang, Zijian Zhang, Sirui Ding, Piotr Mardziel, Xia Hu`
>
> https://ieeexplore.ieee.org/abstract/document/9093360/<br/>
> `Ablation-cam: Visual explanations for deep convolutional network via gradient-free localization. Saurabh Desai and Harish G Ramaswamy. In WACV, pages 972–980, 2020`
>
> https://arxiv.org/abs/2008.02312<br/>
> `Axiom-based Grad-CAM: Towards Accurate Visualization and Explanation of CNNs Ruigang Fu, Qingyong Hu, Xiaohu Dong, Yulan Guo, Yinghui Gao, Biao Li`
>
> https://arxiv.org/abs/2008.00299<br/>
> `Eigen-CAM: Class Activation Map using Principal Components Mohammed Bany Muhammad, Mohammed Yeasin`
>
> http://mftp.mmcheng.net/Papers/21TIP_LayerCAM.pdf<br/>
> `LayerCAM: Exploring Hierarchical Class Activation Maps for Localization Peng-Tao Jiang; Chang-Bin Zhang; Qibin Hou; Ming-Ming Cheng; Yunchao Wei`
>
> https://arxiv.org/abs/1905.00780<br/>
> `Full-Gradient Representation for Neural Network Visualization Suraj Srinivas, Francois Fleuret`
>
> https://arxiv.org/abs/1806.10206<br/>
> `Deep Feature Factorization For Concept Discovery Edo Collins, Radhakrishna Achanta, Sabine Süsstrunk`
>
> https://arxiv.org/abs/2410.00267<br/>
> `KPCA-CAM: Visual Explainability of Deep Computer Vision Models using Kernel PCA Sachin Karmani, Thanushon Sivakaran, Gaurav Prasad, Mehmet Ali, Wenbo Yang, Sheyang Tang`
>
> https://hal.science/hal-02963298/document<br/>
> `Features Understanding in 3D CNNs for Actions Recognition in Video Kazi Ahmed Asif Fuad, Pierre-Etienne Martin, Romain Giot, Romain Bourqui, Jenny Benois-Pineau, Akka Zemmar`
>
> https://arxiv.org/abs/2501.06261<br/>
> `CAMs as Shapley Value-based Explainers Huaiguang Cai`
>
> https://arxiv.org/pdf/2501.11309<br/>
> `Finer-CAM : Spotting the Difference Reveals Finer Details for Visual Explanation`<br/>
> `Ziheng Zhang*, Jianyang Gu*, Arpita Chowdhury, Zheda Mai, David Carlyn,Tanya Berger-Wolf, Yu Su, Wei-Lun Chao`

and tutorial links

> Here you can find detailed examples of how to use this for various custom use cases like object detection:
>
> These point to the new documentation jupter-book for fast rendering. The jupyter notebooks themselves can be found under the tutorials folder in the git repository.
>
> [Notebook tutorial: XAI Recipes for the HuggingFace 🤗 Image Classification Models](https://jacobgil.github.io/pytorch-gradcam-book/HuggingFace.html)
>
> [Notebook tutorial: Deep Feature Factorizations for better model explainability](https://jacobgil.github.io/pytorch-gradcam-book/Deep%20Feature%20Factorizations.html)
>
> [Notebook tutorial: Class Activation Maps for Object Detection with Faster-RCNN](https://jacobgil.github.io/pytorch-gradcam-book/Class%20Activation%20Maps%20for%20Object%20Detection%20With%20Faster%20RCNN.html)
>
> [Notebook tutorial: Class Activation Maps for YOLO5](https://jacobgil.github.io/pytorch-gradcam-book/EigenCAM%20for%20YOLO5.html)
>
> [Notebook tutorial: Class Activation Maps for Semantic Segmentation](https://jacobgil.github.io/pytorch-gradcam-book/Class%20Activation%20Maps%20for%20Semantic%20Segmentation.html)
>
> [Notebook tutorial: Adapting pixel attribution methods for embedding outputs from models](https://jacobgil.github.io/pytorch-gradcam-book/Pixel%20Attribution%20for%20embeddings.html)
>
> [Notebook tutorial: May the best explanation win. CAM Metrics and Tuning](https://jacobgil.github.io/pytorch-gradcam-book/CAM%20Metrics%20And%20Tuning%20Tutorial.html)
>
> [How it works with Vision/SwinT transformers](https://github.com/jacobgil/pytorch-grad-cam/blob/master/tutorials/vision_transformers.md)

#### File structure for repo cloned from @jacobgil

```
$ type atree
atree is aliased to `tree --charset=ascii'

$ atree pytorch-grad-cam/
pytorch-grad-cam/
|-- LICENSE
|-- MANIFEST.in
|-- README.md
|-- cam.py
|-- examples
|   |-- augsmooth.jpg
|   |-- both.png
|   |-- both_detection.png
|   |-- cam_gb_dog.jpg
|   |-- cars_segmentation.png
|   |-- cat.jpg
|   |-- clip_cat.jpg
|   |-- clip_dog.jpg
|   |-- dff1.png
|   |-- dff2.png
|   |-- dog.jpg
|   |-- dog_cat.jfif
|   |-- dogs.png
|   |-- dogs_gradcam++_resnet50.jpg
|   |-- dogs_gradcam++_vgg16.jpg
|   |-- dogs_gradcam_resnet50.jpg
|   |-- dogs_gradcam_vgg16.jpg
|   |-- dogs_scorecam_resnet50.jpg
|   |-- dogs_scorecam_vgg16.jpg
|   |-- eigenaug.jpg
|   |-- eigensmooth.jpg
|   |-- embeddings.png
|   |-- horses.jpg
|   |-- metrics.png
|   |-- multiorgan_segmentation.gif
|   |-- nosmooth.jpg
|   |-- resnet50_cat_ablationcam_cam.jpg
|   |-- resnet50_cat_gradcam_cam.jpg
|   |-- resnet50_cat_scorecam_cam.jpg
|   |-- resnet50_dog_ablationcam_cam.jpg
|   |-- resnet50_dog_gradcam_cam.jpg
|   |-- resnet50_dog_scorecam_cam.jpg
|   |-- resnet_horses_ablationcam_cam.jpg
|   |-- resnet_horses_gradcam++_cam.jpg
|   |-- resnet_horses_gradcam_cam.jpg
|   |-- resnet_horses_horses_eigencam_cam.jpg
|   |-- resnet_horses_scorecam_cam.jpg
|   |-- road.png
|   |-- swinT_cat_ablationcam_cam.jpg
|   |-- swinT_cat_gradcam_cam.jpg
|   |-- swinT_cat_scorecam_cam.jpg
|   |-- swinT_dog_ablationcam_cam.jpg
|   |-- swinT_dog_gradcam_cam.jpg
|   |-- swinT_dog_scorecam_cam.jpg
|   |-- vgg_horses_ablationcam_cam.jpg
|   |-- vgg_horses_eigencam_cam.jpg
|   |-- vgg_horses_gradcam++_cam.jpg
|   |-- vgg_horses_gradcam_cam.jpg
|   |-- vgg_horses_scorecam_cam.jpg
|   |-- vit_cat_ablationcam_cam.jpg
|   |-- vit_cat_gradcam_cam.jpg
|   |-- vit_cat_scorecam_cam.jpg
|   |-- vit_dog_ablationcam_cam.jpg
|   |-- vit_dog_gradcam_cam.jpg
|   |-- vit_dog_scorecam_cam.jpg
|   `-- yolo_eigencam.png
|-- pyproject.toml
|-- pytorch_grad_cam
|   |-- __init__.py
|   |-- ablation_cam.py
|   |-- ablation_cam_multilayer.py
|   |-- ablation_layer.py
|   |-- activations_and_gradients.py
|   |-- base_cam.py
|   |-- eigen_cam.py
|   |-- eigen_grad_cam.py
|   |-- feature_factorization
|   |   |-- __init__.py
|   |   `-- deep_feature_factorization.py
|   |-- fem.py
|   |-- finer_cam.py
|   |-- fullgrad_cam.py
|   |-- grad_cam.py
|   |-- grad_cam_elementwise.py
|   |-- grad_cam_plusplus.py
|   |-- guided_backprop.py
|   |-- hirescam.py
|   |-- kpca_cam.py
|   |-- layer_cam.py
|   |-- metrics
|   |   |-- __init__.py
|   |   |-- cam_mult_image.py
|   |   |-- perturbation_confidence.py
|   |   `-- road.py
|   |-- random_cam.py
|   |-- score_cam.py
|   |-- shapley_cam.py
|   |-- sobel_cam.py
|   |-- utils
|   |   |-- __init__.py
|   |   |-- find_layers.py
|   |   |-- image.py
|   |   |-- model_targets.py
|   |   |-- reshape_transforms.py
|   |   `-- svd_on_activations.py
|   `-- xgrad_cam.py
|-- requirements.txt
|-- setup.cfg
|-- setup.py
|-- tests
|   |-- test_context_release.py
|   |-- test_one_channel.py
|   `-- test_run_all_models.py
|-- tutorials
|   |-- CAM Metrics And Tuning Tutorial.ipynb
|   |-- Class Activation Maps for Object Detection With Faster RCNN.ipynb
|   |-- Class Activation Maps for Semantic Segmentation.ipynb
|   |-- Deep Feature Factorizations.ipynb
|   |-- EigenCAM for YOLO5.ipynb
|   |-- HuggingFace.ipynb
|   |-- Pixel Attribution for embeddings.ipynb
|   |-- bbox.png
|   |-- huggingface_dff.png
|   |-- multimage.png
|   |-- puppies.jpg
|   `-- vision_transformers.md
`-- usage_examples
    |-- clip_example.py
    |-- swinT_example.py
    `-- vit_example.py

8 directories, 117 files

$
```

## Starting on SageMaker

In [ ]:
#only-for-start#!date +'%s_%Y-%m-%dT%H:%M:%S:%z'

Original output when first starting SageMaker

`1750120224_2025-06-17T00:30:24:+0000`<br/>
Local: `2025-06-16T18:30:24-0600`

### Imports, noting deprecated imports that would have been used in previous versions

`Pandas` is complaining on 2025-06-16, so we'll have an

### Install for SageMaker

In [1]:
!pip uninstall -q -y numexpr

#!echo "yes" | pip install -q --exists-action i "numexpr==2.8.4"
#or possibly
!pip install -q --no-input "numexpr==2.8.4"

In [2]:
import numexpr
import pandas as pd

####  In keras.io/examples/vision/grad_cam/ 
####+ (2017 book references, created 2020, modified 2021)
##import os
##os.environ["KERAS_BACKEND"] = "tensorflow"
##from IPython.display import Image, display

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import models
  #  for: Sequential
# from [tensorflow.]keras.models import Sequential
from tensorflow.keras import layers
  #  for: Dense, Activation, Conv2D, MaxPooling2D,
  #+      Dropout, Flatten, Input

#  from [tensorflow.]keras.layers import \
#+               Dense, Dropout, Activation,
#+               Flatten, Conv2D, MaxPooling2D
# from [tensorflow.]keras.layers import Activation
# from [tensorflow.]keras.layers.core import Dense, Flatten
# from [tensorflow.]keras.layers.core import Dropout
# from [tensorflow.]keras.layers.convolutional import Conv2D
# from [tensorflow.]keras.layers.pooling import MaxPooling2D

from tensorflow.keras import optimizers
  # for: Adam
#from [tensorflow.]keras.optimizers import Adam
from tensorflow.keras import metrics
  # for: categorical_crossentropy
#from [tensorflow.]keras.metrics import categorical_crossentropy

from tensorflow.keras import losses
  # for: sparse_categorical_crossentropy
#from [tensorflow.]keras.losses import sparse_categorical_crossentropy

# Callbacks (logging and seeing the model train)
from tensorflow.keras import callbacks
  #  for: CSVLogger, Callback  ## custom callback
  #+      (maybe EarlyStopping, ModelCheckpoint)
#from [tensorflow.]keras.callbacks import CSVLogger

# for Grad-CAM in TensorFlow 2.x
from tensorflow.keras.preprocessing.image import load_img

# Dataset
from tensorflow.keras.datasets import cifar10

##from tensorflow.keras.applications.resnet50 import (
##  ResNet50,
##  preprocess_input,
##  decode_predictions,
##)

import tensorboard

##########################################################

import numpy as np
import random

##----------------
#  Image stuff
##----------------
import cv2
from PIL import ImageFont

import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
  # Remember that Colab doesn't like this.

2025-06-17 00:32:07.972119: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:479] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-06-17 00:32:07.997754: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:10575] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-06-17 00:32:07.997795: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1442] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-06-17 00:32:08.013964: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-06-17 00:32:09.018743: W tensorflow/com

Output (warnings, errors, info) came up as

```
2025-06-16 19:52:06.186069: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:479] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-06-16 19:52:14.321964: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:10575] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-06-16 19:52:14.396558: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1442] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-06-16 19:52:23.964297: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-06-16 19:52:36.233734: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
/home/ec2-user/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/pandas/core/computation/expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.7.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
Matplotlib is building the font cache; this may take a moment.
UsageError: unrecognized arguments: # Remember that Colab doesn't like this.
```

It seems that no installs are needed for SageMaker, though a newer `numexpr` might be nice.

With the `numexpr` install included, I didn't get output. I hope that means everything's okay.

Okay, restarted kernel and cleared output, then I got the following output (later on 2025-06-16 MDT)

```
2025-06-17 00:32:07.972119: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:479] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-06-17 00:32:07.997754: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:10575] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-06-17 00:32:07.997795: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1442] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-06-17 00:32:08.013964: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-06-17 00:32:09.018743: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
```

<strong>Imports for more specialized</strong>

(e.g. looking at documentation, timing things, seeing the date and time)

In [3]:
import inspect
  ## documentation
import timeit
  ## timing (code profiling)
from datetime import datetime
  ## get the date and time

<strong>See if we need installation of stuff here on SageMaker</strong>

In [8]:
!pip install -q --no-input humanfriendly
!pip install -q --no-input visualkeras
!pip install -q --no-input netron
#!pip install quiver_engine

Got an error trying `quiver_engine`, 2025-06-16T18:38:00-0600

```
Collecting quiver_engine
  Using cached quiver_engine-0.1.4.1.4.tar.gz (398 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in quiver_engine setup command: "values of 'package_data' dict" must be of type <tuple[str, ...] | list[str]> (got 'quiverboard/dist/*')
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

In [9]:
import humanfriendly
import visualkeras
import netron
#from quiver_engine import server

## Make sure you check out the environment specifics at the bottom

## Models. Hooray!

### Baseline &ndash; Standard CNNs

### Let's bring in the CIFAR10 Dataset &ndash; Quick and Reckless Import

In [ ]:
#  Let's try with the CIFAR10 Dataset. Why not?
#+ I'm not sure how dataset imports work with tensorflow, so
#+ I'm only importing `cifar10` and not
#+ from tensorflow.keras.datasets import cifar10

## Moving the import up
#from tensorflow.keras.datasets import cifar10

Download the data

In [ ]:
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

### Now to start the inspection and the CNN code!

Pick an image

In [ ]:
image_for_inspection = x_train[0]

Let's have a look at it

In [ ]:
plt.xticks([])
plt.yticks([])
plt.grid(False)
plt.imshow(image_for_inspection)

plt.show()

Inspect the image a bit more, so we know how we need to normalize, etc.

In [ ]:
n_pixels_to_inspect = 5

print(f"Image shape: {image_for_inspection.shape}")
top_corner_array = \
    image_for_inspection[0:n_pixels_to_inspect, :]
print(f"Top left corner values:\n{top_corner_array}")

In [ ]:
print( (
    "\n\nNotice that stacking them side-by-side would give us \n"
    "the RGB values as they'd be seen in the image, but \n"
    "I'm going for quick stuff. Assuming 255 would be okay, \n"
    "or perhaps I should say reasonable, but let's do a better\n"
    "check.\n"
    )
)

print( (
    f"Minimum single RGB value: {min(image_for_inspection.flatten())}\n"
    f"Maximum single RGB value: {max(image_for_inspection.flatten())}"
    )
)

In [ ]:
# Normalize pixel values between 0 and 1
x_train, x_test = x_train / 255.0, x_test / 255.0

In [ ]:
#  Cool visualization of some of our new data, but first
#+ let's double check the image size

print(f"Another image's shape: {x_train[1].shape}")

n_pixels_per_side = 32
n_channels = 3

#  Making sure it's what we expect
assert x_train[1].shape == (n_pixels_per_side,
                            n_pixels_per_side,
                            n_channels
                           )

print("If you've gotten here, the shape is correct, ", end="")
print(f"({n_pixels_per_side}, {n_pixels_per_side}, {n_channels})")

In [ ]:
#  The class names with indexes as defined by CIFAR
class_names = ['airplane', 'automobile', 'bird', 'cat', 'deer',
               'dog', 'frog', 'horse', 'ship', 'truck']

n_classes = len(class_names)

#  Let's show some images
good_figsize_val = 8
plt.figure(figsize=(good_figsize_val, good_figsize_val))

n_rows = 5
n_cols = n_rows  # Let's make our output of images square

n_images_to_show = n_rows * n_cols
for i in range(n_images_to_show):
  plt.subplot(n_rows, n_cols, i+1)
  plt.xticks([])
  plt.yticks([])
  plt.grid(False)
  plt.imshow(x_train[i])
  #  CIFAR labels are arrays, which is
  #+ why we need the extra index.
  plt.xlabel(class_names[y_train[i][0]])
##endof:  for i in range(n_images_to_show)

plt.show()

#### I want to see exactly what the `filters` parameter is. This can be minimized

In [ ]:
print('\n'.join(inspect.getdoc(layers.Conv2D).splitlines()[:54]))

#### I wanted to see exactly what the `filters` parameter was:

```
filters: int, the dimension of the output space (the number of filters
         in the convolution).
```

### Model Construction

### Shell/Skeleton

In [ ]:
model_0 = models.Sequential()  # the shell of our model

### Input Layer

In [ ]:
#  Input layer

n_pix = n_pixels_per_side

in_0 = layers.Input(shape(n_pix, n_pix, n_channels))
model_0.add(in_0)

In [ ]:
model_0.summary()

### First Convolutional Layer

In [ ]:
#  First convolutional layer

n_filters_1 = 32

conv_1 = layers.Conv2D(filters=n_filters_1,
                       kernel_size=(3, 3),
                       padding='same'
                      )

model_0.add(conv_1)
model_0.add(layers.Activation('relu'))

##  Same as
#conv_1_2 = layers.Conv2D(filters=32,
#                         kernel_size=(3, 3),
#                         activation='relu',
#                         padding='same'
#           )

In [ ]:
model_0.summary()

### First Pooling Layer

In [ ]:
#  First pooling layer

pool_1 = layers.MaxPooling2D(pool_size=(2, 2),
                             strides=2,
                             padding='valid'
                            )
  #  Note that `strides=2` is the default for `pool_size=(2,2)`,
  #+ but I want to make sure I see details. `padding='valid'`
  #+ is also default.

model_0.add(pool_1)

In [ ]:
model_0.summary()

### Second Convolutional Layer and Pooling

In [ ]:
n_filters_2 = 64

conv_2 = layers.Conv2D(filters=n_filters_2,
                       kernel_size=(3, 3),
                       padding='same'
                      )

model_0.add(conv_2)
model_0.add(layers.Activation('relu'))

pool_2 = layers.MaxPooling2D(pool_size=(2, 2))

model_0.add(pool_2)

In [ ]:
model_0.summary()

### Third, and for this one, last Convolutional Layer and Pooling

In [ ]:
n_filters_3 = 64

conv_3 = layers.Conv2D(filters=n_filters_3,
                       kernel_size=(3, 3),
                       padding='same'
                      )

model_0.add(conv_3)
model_0.add(layers.Activation('relu'))

pool_3 = layers.MaxPooling2D(pool_size=(2, 2))

model_0.add(pool_3)

In [ ]:
model_0.summary()

### Flattening and the Fully Connected Layer

In [ ]:
#  The Fully Connected layer (after flattening)

model_0.add(layers.Flatten())

fc_layer = layers.Dense(units=64)

model_0.add(fc_layer)
model_0.add(layers.Activation('relu'))

In [ ]:
model_0.summary()

### The Classification Head

In [ ]:
decision_head = layers.Dense(units=n_classes)
model_0.add(decision_head)
##no activation for output (not one-hot encoded)#
##model_0.add(layers.Activation('softmax'))

In [ ]:
model_0.summary()

In [ ]:
print(model_0)

In [ ]:
model_0_str = str(model_0)
print(f"model_0_str: '{model_0_str}'")

The `print` didn't seem so nice &ndash; no super-nice summary or visualization, actually the summarization is incomplete &ndash; so let's look at a few options for visualization.

In [ ]:
visualkeras.layered_view(model_0)

In [ ]:
##  What would have come was
#font = ImageFont.truetype("arial.ttf", 32)
visualkeras.layered_view(model_0, legend=True) #, font=font)

#  Easy fix, just leave out the font parameter

#### Compile Using Optimizer and Loss, Specify Metrics to be Reported

In [ ]:
compile_tic = timeit.default_timer()
model_0.compile(
    optimizer=optimizers.Adam(),  # default learning rate?
    loss=losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics=['accuracy']
)
compile_toc = timeit.default_timer()
print(f"Compile time: {compile_toc - compile_tic:0.4f} seconds")

## Train of it, with both viewing and logging

cf. [tensorboard documentation and example](https://www.tensorflow.org/tensorboard/graphs), which doesn't seem to want to play with the Wayback Machine (archive.org)

In [ ]:
%load_ext tensorboard

In [ ]:
!stat ./tblogs/
# if necessary, also
#!rm -rf ./tblogs/

In [ ]:
#  if necessary, (output is anything but
#+                `stat: cannot statx './tblogs/':`
#+                ` No such file or directory`),
#+
#+ Actually, I just have it telling you it can't if it can't
!rm -rf ./tblogs/ && echo "No problem came up with removal" || \
echo -e "Remvoing ./tblogs/ didn't work\n"\
"likely because it didn't exist\nLet me check ..."
!echo
!echo "Checking stat, whether there's a problem or not"
!stat ./tblogs/ || echo "Not able to stat, dir likely nonexistent"

In [ ]:
logdir = "tblogs/fit/" + datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = callback.TensorBoard(log_dir=logdir)

cf. [StackOverflow Discussion](https://web.archive.org/web/20250423184118/https://stackoverflow.com/questions/67757496/tensorflow-keras-print-out-and-save-loss-and-gradients-during-model-fit)

In [ ]:
class TrainableVariablesCallback(callbacks.Callback):
  def on_epoch_end(self, epoch, logs={}):
    print(model_0.trainable_variables)
  ##endof:  on_epoch_end
##endof:  TrainableVariablesCallback

@todo : Get compute use, memory use, etc. and log, e.g., the trainable variables

If on Colab

<strong>REMEMBER TO CHANGE YOUR RUNTIME TO GPU</strong>

(You might need to re-run old cells, but it's worth it.)

In [ ]:
print(f"Num GPUs Available: {len(tf.config.list_physical_devices('GPU'))}")

In [ ]:
##  This one gives way too much output. If desired, I can
##+ figure out how to send it to a file.
# my_trainable_vars_logger = TrainableVariablesCallback()

!>training.log  # empty the file without deleting the name
my_csv_logger = callbacks.CSVLogger('training.log')

n_epochs = 10

train_tic = timeit.default_timer()

history = model_0.fit(
    x_train, y_train,
    epochs=n_epochs,
    validation_data=(x_test, y_test),
    callbacks=[my_csv_logger,
               #, my_trainable_vars_logger,
               tensorboard_callback
    ]
)

train_toc = timeit.default_timer()
print(f"Train time: {train_toc - train_tic:0.4f} seconds")

train_time_str = format_timespan(train_toc - train_tic)
print(f"which equates to: {train_time_str}")

In [ ]:
%tensorboard --logdir tblogs  #  This seems to be having less problems.
                              #+ It seemed to give nice loss/accuracy
                              #+ that showed we were overfitting by a lot.
                              #+ That problem doesn't seem to be as bad,
                              #+ as you'll probably notice in my plots.
                              #+ The graphs to see the architectures were
                              #+ not all there; and they're still not;
                              #+ Only the "Conceptual graph" shows up.

In [ ]:
##  If you need to do so, and can see the process number it gives you,
##+ you can use that number to kill the TensorBoard server
# !kill 11839

### Standard View of the Accuracy and Loss During Training, maybe more.

In [ ]:
!cat training.log

In [ ]:
plt.plot(history.history['accuracy'], label='accuracy')
plt.plot(history.history['val_accuracy'], label='val_accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.ylim([0.5, 1])
plt.legend(loc='lower right')

In [ ]:
plt.plot(history.history['loss'], label='loss')
plt.plot(history.history['val_loss'], label = 'val_loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.ylim([0, 1.2])
plt.legend(loc='lower right')

That no longer looks like BAD overfitting to me. Maybe I 
had some remnants of previous model builds, or maybe I 
got a bad batch of random starting weights.
(I wish I could see where the initial weights are coming from.)

## And now, run it on our test set ...

... even though the evaluation set we saw above <em>is</em> the test set.

In [ ]:
test_loss, test_acc = \
        model_0.evaluate(x_test, y_test, verbose=2)

Next will come looking at misclassified instances, or at least a look at inference from the model.

## Some details with inference

In [ ]:
this_one_image = x_test[137]

# maybe see if this_one_image is already an array
print(str(type(this_one_image)))

Look at the image.

In [ ]:
plt.xticks([])
plt.yticks([])
plt.grid(False)
plt.imshow(this_one_image)

plt.show()

In [ ]:
img_array = tf.keras.utils.img_to_array(this_one_image)
img_array = tf.expand_dims(img_array, 0)  # Create a batch

In [ ]:
predictions = model.predict(img_array)

print(f" Predictions for each of the classes:\n{predictions}")

In [ ]:
score = tf.nn.softmax(predictions[0])

print(f" Score for each of the classes:\n{score}")

In [ ]:
winning_class = class_names[np.argmax(score)]

print(f"winning_class: {winning_class}")

In [ ]:
print(
    "This image most likely belongs to {} with a {:2f} percent confidence."
    .format(class_names[np.argmax(score)], 100 * np.max(score))
)

In [ ]:
max_idx = 500
n_random_ints = 10
dashes = "--------------------------------------------------------------"
for idx in np.random.randint(1, max_n+1, size=n_random_ints):
  print()
  print()
  print(dashes)
  print()
  this_img = x_test[idx]
  plt.xticks([])
  plt.yticks([])
  plt.grid(False)
  plt.imshow(this_img)
  plt.show()
  print()
  print(f"Ground truth label: {y_test[idx][0]}")
  print()
  img_array = tf.keras.utils.img_to_array(this_image)
  img_array = tf.expand_dims(img_array, 0)  # Create a batch
  predictions = model.predict(img_array)
  print(f" Predictions for each of the classes:\n{predictions}")
  print()
  score = tf.nn.softmax(predictions[0])
  print(f" Score for each of the classes:\n{score}")
  print()
  winning_class = class_names[np.argmax(score)]
  print(f"winning_class: {winning_class}")
  print()
  print("{:2f} percent confidence.".format(100 * np.max(score)))
  print()
  print(dashes)
  print()
##endof:  for idx

#### I'm going to have to look more at how to figure out how to ID and look at misclassified instances

In [ ]:
# code

## Now, let's do the same with Grad-CAM and all other visualizations

Looks like we need to name layers and do some other stuff.

## Here are some nice pictures that will be goals for visualizations <br/>and explanations of Grad-CAM that should help explain things.

Lots of these come from a nice site, learnopencv.com

I feel the creators do a really good job with visualization. The other sources are below all the images.

<br/>
<div>
  <img src="https://raw.githubusercontent.com/bballdave025/rib-wrist-in-bin-din/refs/heads/main/img/cnn_analyticsvidhya.png"
       alt="CNN"
       width="750px">
</div>
<br/>

<br/>
<div>
  <img src="https://raw.githubusercontent.com/bballdave025/rib-wrist-in-bin-din/refs/heads/main/img/cnn_learnopencv_04.png"
       alt="CNN"
       width="750px">
</div>
<br/>

<br/>
<div>
  <img src="https://raw.githubusercontent.com/bballdave025/rib-wrist-in-bin-din/refs/heads/main/img/cnn_learnopencv_05.png"
       alt="CNN"
       width="750px">
</div>
<br/>

<br/>
<div>
  <img src="https://raw.githubusercontent.com/bballdave025/rib-wrist-in-bin-din/refs/heads/main/img/cnn_learnopencv_06.png"
       alt="CNN"
       width="1000px">
</div>
<br/>

<br/>
<div>
  <img src="https://raw.githubusercontent.com/bballdave025/rib-wrist-in-bin-din/refs/heads/main/img/cnn_learnopencv_01.png"
       alt="CNN Code and Architecture Mix"
       width="500px">
</div>
<br/>

That shows a bit how we get to a point where they might trust us. Now observe the Grad-CAM wonder.

<br/>
<div>
  <img src="https://raw.githubusercontent.com/bballdave025/rib-wrist-in-bin-din/refs/heads/main/img/orig_image_grad_camm_fig_2-1.png"
       alt="Grad-CAM Cat and Dog, Original"
       width="500px">
</div>
<br/>

<br/>
<div>
  <img src="https://raw.githubusercontent.com/bballdave025/rib-wrist-in-bin-din/refs/heads/main/img/combination_dog_guidedbackprop_and_gradcam_then_ResNet.png"
       alt="Grad-Cam for dog, combined"
       width="500px">
</div>
<br/>

<br/>
<div>
  <img src="https://raw.githubusercontent.com/bballdave025/rib-wrist-in-bin-din/refs/heads/main/img/combination_dog_guidedbackprop_and_gradcam_then_ResNet.png"
       alt="Grad-Cam Dog details, combined"
       width="500px">
</div>
<br/>

Pretty convincing for me. I would definitely call this explainable AI.

<br/>
<div>
  <img src="https://raw.githubusercontent.com/bballdave025/rib-wrist-in-bin-din/refs/heads/main/img/interesting_semantic_segmentation_gradcam.png"
       alt="Grad-Cam"
       width="500px">
</div>
<br/>

<br/>
<div>
  <img src="https://raw.githubusercontent.com/bballdave025/rib-wrist-in-bin-din/refs/heads/main/img/decisions_for_right_reasons_gender_issue_gradcam.png"
       alt="Grad-Cam important gender issue"
       width="500px">
</div>
<br/>

`https://pyimagesearch.com/2021/07/19/pytorch-training-your-first-convolutional-neural-network-cnn/`

-yGHUa5PL4A

Fine-Tuning ResNet50 A Practical Guide by It's Amit Jan 2025<br/>
https://drive.google.com/file/d/1WHs_NcXro37ByDvsYkocXF6rVfE7DyeQ/view?usp=sharing

Training and Hosting resnet-50 model using Amazon Sagemaker and Flask by Ravi Shukla Nov 2022<br/>
https://drive.google.com/file/d/1RQ7SPUk8ZhJYzDJGpQVASgwCrNC4JqFD/view?usp=sharing

https://adamharley.com/nn_vis/cnn/3d.html

https://github.com/ashishpatel26/Tools-to-Design-or-Visualize-Architecture-of-Neural-Network

https://datascience.stackexchange.com/questions/12851/how-do-you-visualize-neural-network-architectures

https://datascience.stackexchange.com/questions/2670/visualizing-deep-neural-network-training

https://learnopencv.com/understanding-convolutional-neural-networks-cnn/

https://www.analyticsvidhya.com/blog/2020/10/what-is-the-convolutional-neural-network-architecture/

https://www.researchgate.net/figure/The-overall-LeNet-architecture-The-numbers-at-the-convolution-and-pooling-layers_fig2_318972455

https://pyimagesearch.com/2020/03/09/grad-cam-visualize-class-activation-maps-with-keras-tensorflow-and-deep-learning/

https://github.com/jacobgil/pytorch-grad-cam

## Specifics for Colab Environment &ndash; I would<br/>minimize it unless you need to match versions<br/>because things won't work

For this commit / pull request

In [ ]:
#!date +'%s_%Y-%m-%dT%H:%M:%S%z'

Output with this commit:

`1750118934_2025-06-17T00:08:54+0000`

Local: `2025-06-16T18:08:54-0600`

(I'll try to keep this updated for each commit, or at least for each pull request.)

#### Uncomment and run before merging (or after merging) each pull request.

In [11]:
#!pip freeze

Output at `pip freeze` at approximately `1750118934_2025-06-17T00:08:54+0000`

```
absl-py==2.3.0
aggdraw==1.3.19
aiohappyeyeballs @ file:///home/conda/feedstock_root/build_artifacts/aiohappyeyeballs_1741775197943/work
aiohttp @ file:///home/conda/feedstock_root/build_artifacts/aiohttp_1748897545370/work
aiosignal @ file:///home/conda/feedstock_root/build_artifacts/aiosignal_1734342155601/work
alabaster @ file:///home/conda/feedstock_root/build_artifacts/alabaster_1704848697227/work
annotated-types==0.7.0
antlr4-python3-runtime==4.9.3
anyio @ file:///home/conda/feedstock_root/build_artifacts/bld/rattler-build_anyio_1742243108/work
argon2-cffi @ file:///home/conda/feedstock_root/build_artifacts/argon2-cffi_1749017159514/work
argon2-cffi-bindings @ file:///home/conda/feedstock_root/build_artifacts/argon2-cffi-bindings_1725356557095/work
arrow @ file:///home/conda/feedstock_root/build_artifacts/arrow_1733584251875/work
astroid @ file:///home/conda/feedstock_root/build_artifacts/astroid_1746997007492/work
astropy @ file:///home/conda/feedstock_root/build_artifacts/astropy_1732730164730/work
astropy-iers-data @ file:///home/conda/feedstock_root/build_artifacts/astropy-iers-data_1748866287586/work
asttokens @ file:///home/conda/feedstock_root/build_artifacts/asttokens_1733250440834/work
astunparse==1.6.3
async-lru @ file:///home/conda/feedstock_root/build_artifacts/bld/rattler-build_async-lru_1742153708/work
async-timeout @ file:///home/conda/feedstock_root/build_artifacts/async-timeout_1733235340728/work
asyncssh @ file:///home/conda/feedstock_root/build_artifacts/asyncssh_1746470644867/work
atomicwrites @ file:///home/conda/feedstock_root/build_artifacts/atomicwrites_1734603084217/work
attrs==25.3.0
Authlib==1.6.0
autopep8 @ file:///home/conda/feedstock_root/build_artifacts/autopep8_1693061251004/work
autovizwidget @ file:///home/conda/feedstock_root/build_artifacts/autovizwidget_1736983369505/work
awscli==1.40.34
awscrt @ file:///home/conda/feedstock_root/build_artifacts/bld/rattler-build_awscrt_1746842415/work
babel @ file:///home/conda/feedstock_root/build_artifacts/babel_1738490167835/work
backports-datetime-fromisoformat==2.0.3
backports.tarfile @ file:///home/conda/feedstock_root/build_artifacts/backports.tarfile_1733325779670/work
bcrypt @ file:///home/conda/feedstock_root/build_artifacts/bcrypt_1740762453223/work
beautifulsoup4 @ file:///home/conda/feedstock_root/build_artifacts/beautifulsoup4_1744783198182/work
binaryornot @ file:///home/conda/feedstock_root/build_artifacts/binaryornot_1734071693792/work
bitarray @ file:///home/conda/feedstock_root/build_artifacts/bitarray_1748068027752/work
black @ file:///home/conda/feedstock_root/build_artifacts/black-recipe_1742502760723/work
bleach @ file:///home/conda/feedstock_root/build_artifacts/bld/rattler-build_bleach_1737382993/work
blinker @ file:///home/conda/feedstock_root/build_artifacts/blinker_1731096409132/work
bokeh @ file:///home/conda/feedstock_root/build_artifacts/bokeh_1747091499565/work
boto3==1.38.35
botocore==1.38.35
Bottleneck @ file:///home/conda/feedstock_root/build_artifacts/bottleneck_1747241408193/work
Brotli @ file:///home/conda/feedstock_root/build_artifacts/brotli-split_1725267488082/work
brotlipy @ file:///home/conda/feedstock_root/build_artifacts/brotlipy_1725393311144/work
cached-property @ file:///home/conda/feedstock_root/build_artifacts/cached_property_1615209429212/work
certifi @ file:///home/conda/feedstock_root/build_artifacts/certifi_1746569525376/work/certifi
cffi @ file:///home/conda/feedstock_root/build_artifacts/cffi_1725560520483/work
chardet @ file:///home/conda/feedstock_root/build_artifacts/chardet_1741797914774/work
charset-normalizer @ file:///home/conda/feedstock_root/build_artifacts/charset-normalizer_1746214863626/work
click==8.1.8
cloudpickle @ file:///home/conda/feedstock_root/build_artifacts/cloudpickle_1736947526808/work
colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1733218098505/work
comm @ file:///home/conda/feedstock_root/build_artifacts/comm_1733502965406/work
contourpy @ file:///home/conda/feedstock_root/build_artifacts/contourpy_1744743067588/work
cookiecutter @ file:///home/conda/feedstock_root/build_artifacts/cookiecutter_1734069695401/work
coverage @ file:///home/conda/feedstock_root/build_artifacts/coverage_1748048692470/work
cryptography==45.0.3
cycler @ file:///home/conda/feedstock_root/build_artifacts/cycler_1733332471406/work
Cython @ file:///home/conda/feedstock_root/build_artifacts/cython_1747670283756/work
cytoolz @ file:///home/conda/feedstock_root/build_artifacts/cytoolz_1734107196509/work
dask @ file:///home/conda/feedstock_root/build_artifacts/dask-core_1747771612930/work
debugpy @ file:///home/conda/feedstock_root/build_artifacts/debugpy_1744321252239/work
decorator @ file:///home/conda/feedstock_root/build_artifacts/decorator_1740384970518/work
defusedxml @ file:///home/conda/feedstock_root/build_artifacts/defusedxml_1615232257335/work
Deprecated @ file:///home/conda/feedstock_root/build_artifacts/deprecated_1737986966356/work
diff-match-patch @ file:///home/conda/feedstock_root/build_artifacts/diff-match-patch_1734637534167/work
dill @ file:///home/conda/feedstock_root/build_artifacts/dill_1744798524990/work
distributed @ file:///home/conda/feedstock_root/build_artifacts/distributed_1747775339483/work
distro @ file:///home/conda/feedstock_root/build_artifacts/distro_1675116244235/work
docker==7.1.0
docstring-to-markdown @ file:///home/conda/feedstock_root/build_artifacts/bld/rattler-build_docstring-to-markdown_1746284388/work
docutils @ file:///home/conda/feedstock_root/build_artifacts/docutils_1666754874910/work
dparse==0.6.4
entrypoints @ file:///home/conda/feedstock_root/build_artifacts/entrypoints_1733327148154/work
et_xmlfile @ file:///home/conda/feedstock_root/build_artifacts/et_xmlfile_1733749653422/work
exceptiongroup @ file:///home/conda/feedstock_root/build_artifacts/exceptiongroup_1746947292760/work
executing @ file:///home/conda/feedstock_root/build_artifacts/executing_1745502089858/work
fastapi==0.115.12
fastcache @ file:///home/conda/feedstock_root/build_artifacts/fastcache_1725746788488/work
fastjsonschema @ file:///home/conda/feedstock_root/build_artifacts/python-fastjsonschema_1733235979760/work/dist
filelock==3.16.1
flake8 @ file:///home/conda/feedstock_root/build_artifacts/flake8_1739898391164/work
Flask @ file:///home/conda/feedstock_root/build_artifacts/flask_1747203985407/work
flask-cors @ file:///home/conda/feedstock_root/build_artifacts/bld/rattler-build_flask-cors_1747515361/work
flatbuffers==25.2.10
fonttools @ file:///home/conda/feedstock_root/build_artifacts/fonttools_1748465473694/work
fqdn @ file:///home/conda/feedstock_root/build_artifacts/fqdn_1733327382592/work/dist
frozenlist @ file:///home/conda/feedstock_root/build_artifacts/frozenlist_1746635328256/work
fsspec @ file:///home/conda/feedstock_root/build_artifacts/fsspec_1748101524683/work
future @ file:///home/conda/feedstock_root/build_artifacts/future_1738926421307/work
gast==0.6.0
gevent @ file:///home/conda/feedstock_root/build_artifacts/gevent_1747078508282/work
gmpy2 @ file:///home/conda/feedstock_root/build_artifacts/gmpy2_1745509363766/work
google-pasta==0.2.0
graphene==3.4.3
graphql-core==3.2.6
graphql-relay==3.2.0
greenlet @ file:///home/conda/feedstock_root/build_artifacts/greenlet_1746824031437/work
grpcio==1.72.1
gssapi @ file:///home/conda/feedstock_root/build_artifacts/python-gssapi_1733827675249/work
gym==0.26.2
gym-notices==0.0.8
h11==0.16.0
h2 @ file:///home/conda/feedstock_root/build_artifacts/h2_1738578511449/work
h5py @ file:///home/conda/feedstock_root/build_artifacts/h5py_1739952247544/work
hdijupyterutils @ file:///home/conda/feedstock_root/build_artifacts/hdijupyterutils_1736983344385/work
hpack @ file:///home/conda/feedstock_root/build_artifacts/hpack_1737618293087/work
humanfriendly==10.0
hyperframe @ file:///home/conda/feedstock_root/build_artifacts/hyperframe_1737618333194/work
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1733211830134/work
imagecodecs-lite @ file:///home/conda/feedstock_root/build_artifacts/imagecodecs-lite_1716011160511/work
imageio @ file:///home/conda/feedstock_root/build_artifacts/imageio_1738273805233/work
imagesize @ file:///home/conda/feedstock_root/build_artifacts/imagesize_1656939531508/work
immutables @ file:///home/conda/feedstock_root/build_artifacts/immutables_1747742326998/work
importlib-metadata==6.11.0
importlib_resources @ file:///home/conda/feedstock_root/build_artifacts/importlib_resources_1736252299705/work
inflection @ file:///home/conda/feedstock_root/build_artifacts/inflection_1734732140003/work
iniconfig @ file:///home/conda/feedstock_root/build_artifacts/iniconfig_1733223141826/work
intervaltree @ file:///home/conda/feedstock_root/build_artifacts/intervaltree_1683532206518/work
ipykernel @ file:///home/conda/feedstock_root/build_artifacts/ipykernel_1719845459717/work
ipython @ file:///home/conda/feedstock_root/build_artifacts/ipython_1698846603011/work
ipywidgets @ file:///home/conda/feedstock_root/build_artifacts/ipywidgets_1746454582739/work
isoduration @ file:///home/conda/feedstock_root/build_artifacts/isoduration_1733493628631/work/dist
isort @ file:///home/conda/feedstock_root/build_artifacts/isort_1746190248328/work
itsdangerous @ file:///home/conda/feedstock_root/build_artifacts/itsdangerous_1733308265247/work
jaraco.classes @ file:///home/conda/feedstock_root/build_artifacts/jaraco.classes_1733325873251/work
jaraco.context @ file:///home/conda/feedstock_root/build_artifacts/jaraco.context_1733382590553/work
jaraco.functools @ file:///home/conda/feedstock_root/build_artifacts/jaraco.functools_1733746366381/work
jedi @ file:///home/conda/feedstock_root/build_artifacts/jedi_1733300866624/work
jeepney @ file:///home/conda/feedstock_root/build_artifacts/jeepney_1740828240267/work
jellyfish @ file:///home/conda/feedstock_root/build_artifacts/jellyfish_1734444752947/work
Jinja2 @ file:///home/conda/feedstock_root/build_artifacts/jinja2_1741263328855/work
jmespath @ file:///home/conda/feedstock_root/build_artifacts/jmespath_1733229141657/work
joblib @ file:///home/conda/feedstock_root/build_artifacts/joblib_1748019130050/work
json5 @ file:///home/conda/feedstock_root/build_artifacts/json5_1743722064131/work
jsonpointer @ file:///home/conda/feedstock_root/build_artifacts/jsonpointer_1725302897999/work
jsonschema @ file:///home/conda/feedstock_root/build_artifacts/jsonschema_1748294245630/work
jsonschema-specifications @ file:///tmp/tmpuvkyqc9y/src
jupyter @ file:///home/conda/feedstock_root/build_artifacts/jupyter_1733818543322/work
jupyter-console @ file:///home/conda/feedstock_root/build_artifacts/jupyter_console_1733817997778/work
jupyter-events @ file:///home/conda/feedstock_root/build_artifacts/bld/rattler-build_jupyter_events_1738765986/work
jupyter-lsp @ file:///home/conda/feedstock_root/build_artifacts/bld/rattler-build_jupyter-lsp_1748550130/work/jupyter-lsp
jupyter_client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1733440914442/work
jupyter_core @ file:///home/conda/feedstock_root/build_artifacts/jupyter_core_1748333051527/work
jupyter_server @ file:///home/conda/feedstock_root/build_artifacts/bld/rattler-build_jupyter_server_1747083217/work
jupyter_server_terminals @ file:///home/conda/feedstock_root/build_artifacts/jupyter_server_terminals_1733427956852/work
jupyterlab @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_1748272853841/work
jupyterlab_pygments @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_pygments_1733328101776/work
jupyterlab_server @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_server_1733599573484/work
jupyterlab_widgets @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_widgets_1746450771080/work
keras==3.10.0
keyring @ file:///home/conda/feedstock_root/build_artifacts/keyring_1735210185992/work
kiwisolver @ file:///home/conda/feedstock_root/build_artifacts/kiwisolver_1725459213453/work
krb5 @ file:///home/conda/feedstock_root/build_artifacts/pykrb5_1741302027048/work
lazy-object-proxy @ file:///home/conda/feedstock_root/build_artifacts/lazy-object-proxy_1744895524715/work
lazy_loader @ file:///home/conda/feedstock_root/build_artifacts/lazy-loader_1733636780672/work
libclang==18.1.1
lief @ file:///home/conda/feedstock_root/build_artifacts/lief_1743551769507/work/api/python
llvmlite==0.44.0
locket @ file:///home/conda/feedstock_root/build_artifacts/locket_1650660393415/work
lz4 @ file:///home/conda/feedstock_root/build_artifacts/lz4_1746561905891/work
Markdown==3.8
markdown-it-py @ file:///home/conda/feedstock_root/build_artifacts/markdown-it-py_1733250460757/work
MarkupSafe @ file:///home/conda/feedstock_root/build_artifacts/markupsafe_1733219680183/work
marshmallow==4.0.0
matplotlib==3.10.3
matplotlib-inline @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-inline_1733416936468/work
mccabe @ file:///home/conda/feedstock_root/build_artifacts/mccabe_1733216466933/work
mdurl @ file:///home/conda/feedstock_root/build_artifacts/mdurl_1733255585584/work
mistune @ file:///home/conda/feedstock_root/build_artifacts/bld/rattler-build_mistune_1742402716/work
mkl-service==2.4.2
mkl_fft==1.3.14
ml-dtypes==0.3.2
mock==4.0.3
more-itertools @ file:///home/conda/feedstock_root/build_artifacts/more-itertools_1745349462661/work
mpi4py==4.0.3
mpmath @ file:///home/conda/feedstock_root/build_artifacts/mpmath_1733302684489/work
msgpack @ file:///home/conda/feedstock_root/build_artifacts/msgpack-python_1725974993022/work
multidict @ file:///home/conda/feedstock_root/build_artifacts/multidict_1747722347633/work
multiprocess==0.70.18
munkres==1.1.4
mypy_extensions @ file:///home/conda/feedstock_root/build_artifacts/mypy_extensions_1745776566517/work
namex==0.1.0
narwhals @ file:///home/conda/feedstock_root/build_artifacts/bld/rattler-build_narwhals_1748271935/work
nbclient @ file:///home/conda/feedstock_root/build_artifacts/nbclient_1734628800805/work
nbconvert @ file:///home/conda/feedstock_root/build_artifacts/bld/rattler-build_nbconvert-core_1738067871/work
nbformat @ file:///home/conda/feedstock_root/build_artifacts/nbformat_1733402752141/work
nest_asyncio @ file:///home/conda/feedstock_root/build_artifacts/nest-asyncio_1733325553580/work
netron==8.3.9
networkx @ file:///home/conda/feedstock_root/build_artifacts/bld/rattler-build_networkx_1731521053/work
nltk @ file:///home/conda/feedstock_root/build_artifacts/nltk_1734309924703/work
notebook @ file:///home/conda/feedstock_root/build_artifacts/notebook_1748278664848/work
notebook_shim @ file:///home/conda/feedstock_root/build_artifacts/notebook-shim_1733408315203/work
numba @ file:///home/conda/feedstock_root/build_artifacts/numba_1744232039266/work
numexpr==2.8.4
numpy @ file:///home/conda/feedstock_root/build_artifacts/numpy_1707225380409/work/dist/numpy-1.26.4-cp310-cp310-linux_x86_64.whl#sha256=51131fd8fc130cd168aecaf1bc0ea85f92e8ffebf211772ceb16ac2e7f10d7ca
numpydoc @ file:///home/conda/feedstock_root/build_artifacts/numpydoc_1733650859674/work
nvidia-ml-py @ file:///home/conda/feedstock_root/build_artifacts/nvidia-ml-py_1746576379096/work
omegaconf==2.3.0
opencv-python==4.11.0.86
openpyxl @ file:///home/conda/feedstock_root/build_artifacts/openpyxl_1725460826776/work
opt_einsum==3.4.0
optree==0.16.0
overrides @ file:///home/conda/feedstock_root/build_artifacts/overrides_1734587627321/work
packaging==24.2
pandas @ file:///home/conda/feedstock_root/build_artifacts/pandas_1726878398774/work
pandocfilters @ file:///home/conda/feedstock_root/build_artifacts/pandocfilters_1631603243851/work
parso @ file:///home/conda/feedstock_root/build_artifacts/parso_1733271261340/work
partd @ file:///home/conda/feedstock_root/build_artifacts/partd_1715026491486/work
path @ file:///home/conda/feedstock_root/build_artifacts/path_1737244316269/work
pathlib2 @ file:///home/conda/feedstock_root/build_artifacts/pathlib2_1725350144616/work
pathos==0.3.4
pathspec @ file:///home/conda/feedstock_root/build_artifacts/pathspec_1733233363808/work
patsy @ file:///home/conda/feedstock_root/build_artifacts/patsy_1733792384640/work
pexpect @ file:///home/conda/feedstock_root/build_artifacts/pexpect_1733301927746/work
pickleshare @ file:///home/conda/feedstock_root/build_artifacts/pickleshare_1733327343728/work
pillow @ file:///home/conda/feedstock_root/build_artifacts/pillow_1746646209821/work
pkginfo @ file:///home/conda/feedstock_root/build_artifacts/pkginfo_1739984581450/work
pkgutil_resolve_name @ file:///home/conda/feedstock_root/build_artifacts/pkgutil-resolve-name_1733344503739/work
platformdirs @ file:///home/conda/feedstock_root/build_artifacts/bld/rattler-build_platformdirs_1746710438/work
plotly @ file:///home/conda/feedstock_root/build_artifacts/plotly_1748388440098/work
pluggy @ file:///home/conda/feedstock_root/build_artifacts/pluggy_1747339660894/work
ply @ file:///home/conda/feedstock_root/build_artifacts/ply_1733239724146/work
pox==0.3.6
ppft==1.7.7
prometheus_client @ file:///home/conda/feedstock_root/build_artifacts/prometheus_client_1748896729786/work
prompt-toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1677600924538/work
propcache @ file:///home/conda/feedstock_root/build_artifacts/propcache_1744524934684/work
protobuf==4.25.8
psutil==6.1.1
psycopg2 @ file:///home/conda/feedstock_root/build_artifacts/psycopg2-split_1727892677567/work
psycopg2-binary @ file:///home/conda/feedstock_root/build_artifacts/psycopg2-split_1701737547976/work/psycopg2-binary
ptyprocess @ file:///home/conda/feedstock_root/build_artifacts/ptyprocess_1733302279685/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl#sha256=92c32ff62b5fd8cf325bec5ab90d7be3d2a8ca8c8a3813ff487a8d2002630d1f
pure_eval @ file:///home/conda/feedstock_root/build_artifacts/pure_eval_1733569405015/work
py-cpuinfo @ file:///home/conda/feedstock_root/build_artifacts/py-cpuinfo_1733236359728/work
py4j==0.10.9.5
pyarrow==18.1.0
pyasn1==0.6.1
pybind11 @ file:///D:/bld/pybind11-split_1747934313674/work
pybind11_global @ file:///home/conda/feedstock_root/build_artifacts/pybind11-split_1747934270866/work
pycodestyle @ file:///home/conda/feedstock_root/build_artifacts/pycodestyle_1733216196861/work
pyconify @ file:///home/conda/feedstock_root/build_artifacts/pyconify_1738865203119/work
pycosat @ file:///home/conda/feedstock_root/build_artifacts/pycosat_1732588391741/work
pycparser @ file:///home/conda/feedstock_root/build_artifacts/bld/rattler-build_pycparser_1733195786/work
pycryptodome @ file:///home/conda/feedstock_root/build_artifacts/pycryptodome_1747561177604/work
pycurl @ file:///home/conda/feedstock_root/build_artifacts/pycurl_1741333902605/work
pydantic==2.9.2
pydantic_core==2.23.4
pydocstyle @ file:///home/conda/feedstock_root/build_artifacts/pydocstyle_1733261631732/work
pyerfa @ file:///home/conda/feedstock_root/build_artifacts/pyerfa_1731377671994/work
pyflakes @ file:///home/conda/feedstock_root/build_artifacts/pyflakes_1733216066937/work
pyfunctional==1.5.0
pygame==2.6.1
PyGithub @ file:///home/conda/feedstock_root/build_artifacts/pygithub_1740204758187/work
Pygments @ file:///home/conda/feedstock_root/build_artifacts/pygments_1736243443484/work
PyJWT @ file:///home/conda/feedstock_root/build_artifacts/pyjwt_1732782409051/work
pykerberos @ file:///home/conda/feedstock_root/build_artifacts/pykerberos_1725289118206/work
pylint @ file:///home/conda/feedstock_root/build_artifacts/bld/rattler-build_pylint_1746387959/work
pylint-venv @ file:///home/conda/feedstock_root/build_artifacts/pylint-venv_1734789278875/work
pyls-spyder @ file:///home/conda/feedstock_root/build_artifacts/pyls-spyder_1736029828480/work
PyNaCl @ file:///home/conda/feedstock_root/build_artifacts/pynacl_1725739248276/work
pynvml @ file:///home/conda/feedstock_root/build_artifacts/pynvml_1734538935786/work
pyodbc @ file:///home/conda/feedstock_root/build_artifacts/pyodbc_1729084271546/work
pyOpenSSL @ file:///home/conda/feedstock_root/build_artifacts/pyopenssl_1747560772891/work
pyparsing @ file:///home/conda/feedstock_root/build_artifacts/pyparsing_1743089729650/work
PyQt5==5.15.11
PyQt5_sip==12.17.0
PyQtWebEngine==5.15.7
pyrsistent @ file:///home/conda/feedstock_root/build_artifacts/pyrsistent_1725353509161/work
PySide6==6.9.1
PySocks @ file:///home/conda/feedstock_root/build_artifacts/pysocks_1733217236728/work
pyspark==3.3.0
pyspnego @ file:///home/conda/feedstock_root/build_artifacts/pyspnego_1731411726251/work
pytest @ file:///home/conda/feedstock_root/build_artifacts/pytest_1748907508048/work
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1709299778482/work
python-json-logger @ file:///home/conda/feedstock_root/build_artifacts/python-json-logger_1677079630776/work
python-lsp-black @ file:///home/conda/feedstock_root/build_artifacts/python-lsp-black_1736029913871/work
python-lsp-jsonrpc @ file:///home/conda/feedstock_root/build_artifacts/python-lsp-jsonrpc_1736013464386/work
python-lsp-server @ file:///home/conda/feedstock_root/build_artifacts/python-lsp-server-meta_1739028314576/work
python-slugify @ file:///home/conda/feedstock_root/build_artifacts/python-slugify_1733756245724/work
pytoolconfig @ file:///home/conda/feedstock_root/build_artifacts/pytoolconfig_1733360721313/work
pytz @ file:///home/conda/feedstock_root/build_artifacts/pytz_1706886791323/work
pyuca @ file:///home/conda/feedstock_root/build_artifacts/pyuca_1734685489013/work
PyWavelets==1.8.0
pyxdg @ file:///home/conda/feedstock_root/build_artifacts/pyxdg_1654536799286/work
PyYAML @ file:///home/conda/feedstock_root/build_artifacts/pyyaml_1737454647378/work
pyzmq @ file:///home/conda/feedstock_root/build_artifacts/pyzmq_1743831255788/work
QDarkStyle @ file:///home/conda/feedstock_root/build_artifacts/qdarkstyle_1736088649807/work
qstylizer @ file:///home/conda/feedstock_root/build_artifacts/qstylizer_1732204919793/work/dist/qstylizer-0.2.4-py2.py3-none-any.whl#sha256=020f9e24a101c9478a6b32575838b93eeefacc8887520a67c172ba33ad22aa2c
QtAwesome @ file:///home/conda/feedstock_root/build_artifacts/qtawesome_1741041188600/work
qtconsole @ file:///home/conda/feedstock_root/build_artifacts/qtconsole-base_1733730417233/work
QtPy @ file:///home/conda/feedstock_root/build_artifacts/qtpy_1739289837248/work
referencing @ file:///home/conda/feedstock_root/build_artifacts/bld/rattler-build_referencing_1737836872/work
regex @ file:///home/conda/feedstock_root/build_artifacts/regex_1730952192772/work
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1733217035951/work
requests-kerberos @ file:///home/conda/feedstock_root/build_artifacts/requests-kerberos_1733915992449/work
rfc3339_validator @ file:///home/conda/feedstock_root/build_artifacts/rfc3339-validator_1733599910982/work
rfc3986-validator @ file:///home/conda/feedstock_root/build_artifacts/rfc3986-validator_1598024191506/work
rich @ file:///home/conda/feedstock_root/build_artifacts/bld/rattler-build_rich_1743371105/work/dist
rope @ file:///home/conda/feedstock_root/build_artifacts/rope_1733342323938/work
rpds-py @ file:///home/conda/feedstock_root/build_artifacts/bld/rattler-build_rpds-py_1747837825/work
rsa==4.7.2
rtree @ file:///home/conda/feedstock_root/build_artifacts/rtree_1741378561624/work
ruamel-yaml-conda @ file:///home/conda/feedstock_root/build_artifacts/ruamel_yaml_1695546328261/work
ruamel.yaml @ file:///home/conda/feedstock_root/build_artifacts/ruamel.yaml_1678272977710/work
ruamel.yaml.clib @ file:///home/conda/feedstock_root/build_artifacts/ruamel.yaml.clib_1728724455198/work
s3fs==0.4.2
s3transfer @ file:///home/conda/feedstock_root/build_artifacts/s3transfer_1747960786701/work
safety-schemas==0.0.14
sagemaker==2.246.0
sagemaker-core==1.0.36
sagemaker_pyspark==1.4.5
schema==0.7.7
scikit-image @ file:///home/conda/feedstock_root/build_artifacts/scikit-image_1681313146947/work/dist/scikit_image-0.20.0-cp310-cp310-linux_x86_64.whl
scikit-learn @ file:///home/conda/feedstock_root/build_artifacts/scikit-learn_1736496756180/work/dist/scikit_learn-1.6.1-cp310-cp310-linux_x86_64.whl#sha256=8b3481924bda36bf9a85c5f500f48e43e1178ead014b2d2ecf10f7b9b49935b4
scipy @ file:///home/conda/feedstock_root/build_artifacts/scipy-split_1739790642651/work/dist/scipy-1.15.2-cp310-cp310-linux_x86_64.whl#sha256=9e52bad6c3294d1a5b04a13632118ca2157130603c6c018c2d710162b223b27e
seaborn @ file:///home/conda/feedstock_root/build_artifacts/seaborn-split_1733730015268/work
SecretStorage @ file:///home/conda/feedstock_root/build_artifacts/secretstorage_1725915608929/work
Send2Trash @ file:///home/conda/feedstock_root/build_artifacts/send2trash_1733322040660/work
shap @ file:///home/conda/feedstock_root/build_artifacts/shap_1744972817899/work
shellingham==1.5.4
shiboken6==6.9.1
sip @ file:///home/conda/feedstock_root/build_artifacts/sip_1745411202924/work
six @ file:///home/conda/feedstock_root/build_artifacts/six_1733380938961/work
slicer @ file:///home/conda/feedstock_root/build_artifacts/slicer_1710029110974/work
smclarify==0.5
smdebug-rulesconfig==1.0.1
sniffio @ file:///home/conda/feedstock_root/build_artifacts/sniffio_1733244044561/work
snowballstemmer @ file:///home/conda/feedstock_root/build_artifacts/snowballstemmer_1747749415787/work
sortedcontainers @ file:///home/conda/feedstock_root/build_artifacts/sortedcontainers_1738440353519/work
soupsieve @ file:///home/conda/feedstock_root/build_artifacts/soupsieve_1746563585861/work
sparkmagic==0.22.0
Sphinx @ file:///home/conda/feedstock_root/build_artifacts/sphinx_1713554891974/work
sphinxcontrib-applehelp @ file:///home/conda/feedstock_root/build_artifacts/sphinxcontrib-applehelp_1733754101641/work
sphinxcontrib-devhelp @ file:///home/conda/feedstock_root/build_artifacts/sphinxcontrib-devhelp_1733754113405/work
sphinxcontrib-htmlhelp @ file:///home/conda/feedstock_root/build_artifacts/sphinxcontrib-htmlhelp_1733754280555/work
sphinxcontrib-jsmath @ file:///home/conda/feedstock_root/build_artifacts/sphinxcontrib-jsmath_1733753744933/work
sphinxcontrib-qthelp @ file:///home/conda/feedstock_root/build_artifacts/sphinxcontrib-qthelp_1733753408017/work
sphinxcontrib-serializinghtml @ file:///home/conda/feedstock_root/build_artifacts/sphinxcontrib-serializinghtml_1733750479108/work
sphinxcontrib-websupport @ file:///home/conda/feedstock_root/build_artifacts/sphinxcontrib-websupport_1705125899521/work
spyder @ file:///home/conda/feedstock_root/build_artifacts/spyder-base_1747952905431/work
spyder-kernels @ file:///home/conda/feedstock_root/build_artifacts/spyder-kernels_1747849464559/work
SQLAlchemy @ file:///home/conda/feedstock_root/build_artifacts/sqlalchemy_1747298815541/work
stack_data @ file:///home/conda/feedstock_root/build_artifacts/stack_data_1733569443808/work
starlette==0.46.2
statsmodels @ file:///home/conda/feedstock_root/build_artifacts/statsmodels_1727986707121/work
superqt @ file:///home/conda/feedstock_root/build_artifacts/superqt_1743212840100/work
sympy @ file:///home/conda/feedstock_root/build_artifacts/sympy_1745946051654/work
tables @ file:///home/conda/feedstock_root/build_artifacts/pytables_1733265846456/work
tabulate @ file:///home/conda/feedstock_root/build_artifacts/tabulate_1733589744265/work
tblib @ file:///home/conda/feedstock_root/build_artifacts/tblib_1743515515538/work
tenacity==9.1.2
tensorboard==2.16.2
tensorboard-data-server==0.7.2
tensorflow==2.16.2
tensorflow-io-gcs-filesystem==0.37.1
termcolor==3.1.0
terminado @ file:///home/conda/feedstock_root/build_artifacts/terminado_1710262609923/work
testpath @ file:///home/conda/feedstock_root/build_artifacts/testpath_1733327295736/work
text-unidecode @ file:///home/conda/feedstock_root/build_artifacts/text-unidecode_1733749896243/work
textdistance @ file:///home/conda/feedstock_root/build_artifacts/textdistance_1736082828021/work
tf_keras==2.16.0
threadpoolctl @ file:///home/conda/feedstock_root/build_artifacts/threadpoolctl_1741878222898/work
three-merge @ file:///home/conda/feedstock_root/build_artifacts/three-merge_1736031697739/work
tifffile @ file:///home/conda/feedstock_root/build_artifacts/tifffile_1591280222285/work
tinycss2 @ file:///home/conda/feedstock_root/build_artifacts/tinycss2_1729802851396/work
toml @ file:///home/conda/feedstock_root/build_artifacts/toml_1734091811753/work
tomli @ file:///home/conda/feedstock_root/build_artifacts/tomli_1733256695513/work
tomlkit @ file:///home/conda/feedstock_root/build_artifacts/tomlkit_1733230743009/work
toolz @ file:///home/conda/feedstock_root/build_artifacts/toolz_1733736030883/work
tornado @ file:///home/conda/feedstock_root/build_artifacts/tornado_1748003301700/work
tqdm @ file:///home/conda/feedstock_root/build_artifacts/tqdm_1735661334605/work
traitlets @ file:///home/conda/feedstock_root/build_artifacts/traitlets_1733367359838/work
typed-ast @ file:///home/conda/feedstock_root/build_artifacts/typed-ast_1695409894288/work
typer==0.16.0
types-python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/types-python-dateutil_1747417193651/work
typing-inspection==0.4.1
typing_extensions @ file:///home/conda/feedstock_root/build_artifacts/bld/rattler-build_typing_extensions_1748959427/work
typing_utils @ file:///home/conda/feedstock_root/build_artifacts/typing_utils_1733331286120/work
tzdata @ file:///home/conda/feedstock_root/build_artifacts/python-tzdata_1742745135198/work
ujson @ file:///home/conda/feedstock_root/build_artifacts/ujson_1724954402136/work
unicodedata2 @ file:///home/conda/feedstock_root/build_artifacts/unicodedata2_1736692496989/work
uri-template @ file:///home/conda/feedstock_root/build_artifacts/uri-template_1733323593477/work/dist
urllib3 @ file:///home/conda/feedstock_root/build_artifacts/urllib3_1718728347128/work
uvicorn==0.34.3
visualkeras==0.1.4
watchdog @ file:///home/conda/feedstock_root/build_artifacts/watchdog_1730492868936/work
wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1733231326287/work
webcolors @ file:///home/conda/feedstock_root/build_artifacts/webcolors_1733359735138/work
webencodings @ file:///home/conda/feedstock_root/build_artifacts/webencodings_1733236011802/work
websocket-client @ file:///home/conda/feedstock_root/build_artifacts/websocket-client_1733157342724/work
Werkzeug @ file:///home/conda/feedstock_root/build_artifacts/werkzeug_1733160440960/work
whatthepatch @ file:///home/conda/feedstock_root/build_artifacts/whatthepatch_1736040839611/work
widgetsnbextension @ file:///home/conda/feedstock_root/build_artifacts/widgetsnbextension_1744291053367/work
wrapt @ file:///home/conda/feedstock_root/build_artifacts/wrapt_1736869474897/work
wurlitzer @ file:///home/conda/feedstock_root/build_artifacts/wurlitzer_1736089142811/work
XlsxWriter @ file:///home/conda/feedstock_root/build_artifacts/xlsxwriter_1745134629697/work
xyzservices @ file:///home/conda/feedstock_root/build_artifacts/xyzservices_1745598038694/work
yapf @ file:///home/conda/feedstock_root/build_artifacts/yapf_1736192735449/work
yarl @ file:///home/conda/feedstock_root/build_artifacts/yarl_1744972437465/work
zict @ file:///home/conda/feedstock_root/build_artifacts/zict_1733261551178/work
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1748277385522/work
zope.event @ file:///home/conda/feedstock_root/build_artifacts/zope.event_1732754803800/work
zope.interface @ file:///home/conda/feedstock_root/build_artifacts/zope.interface_1732794946912/work
zstandard==0.23.0
```