#!/usr/bin/env bash

# Create a minimal, idempotent RMMFB experiment scaffold.
#
# Usage:
#   ./structure.sh <ROOT_DIR> <tag1> [tag2 ...]
#   WITH_NB_STUBS=1 ./structure.sh <ROOT_DIR> <tag1> [tag2 ...]
#   ./structure.sh --check <ROOT_DIR> <tag>
#
# structure.sh creates experiment structure.
# Repository-level concerns such as line-ending policy belong in
# .gitattributes rather than in this script.

set -euo pipefail

usage() {
  cat <<EOF_USAGE
Usage:
  $0 <ROOT_DIR> <tag1> [tag2 ...]

Optionally:
  WITH_NB_STUBS=1 $0 <ROOT_DIR> <tag1> [tag2 ...]

Check an existing scaffold:
  $0 --check <ROOT_DIR> <tag>

Creates an idempotent experiment scaffold.
If WITH_NB_STUBS=1, new notebooks are initialized as valid minimal
Jupyter notebooks rather than empty placeholder files.
Existing files are not overwritten.
EOF_USAGE
}

mkd() {
  mkdir -p -- "$1"
}

touch_safe() {
  local path="$1"
  mkd "$(dirname -- "$path")"
  [ -f "$path" ] || : > "$path"
}

emit_ipynb() {
  local path="$1"

  python - "$path" <<'PY'
import json
import sys

nb = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# RMMFB experiment notebook\n",
                "\n",
                "Generated by `structure.sh`. Replace or extend this stub for the experiment.\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import random\n",
                "import numpy as np\n",
                "\n",
                "SEED = 137\n",
                "random.seed(SEED)\n",
                "np.random.seed(SEED)\n",
            ],
        },
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3 (ipykernel)",
            "language": "python",
            "name": "python3",
        },
        "language_info": {
            "name": "python",
        },
    },
    "nbformat": 4,
    "nbformat_minor": 5,
}

with open(sys.argv[1], "w", encoding="utf-8") as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)
    f.write("\n")
PY
}

check_scaffold() {
  local root_dir="$1"
  local tag="$2"
  local tag_dir="${root_dir%/}/$tag"
  local tag_name
  tag_name="$(basename -- "$tag")"

  local missing=0

  check_path() {
    local rel="$1"
    if [ ! -e "$tag_dir/$rel" ]; then
      printf 'MISSING: %s\n' "$tag_dir/$rel"
      missing=1
    fi
  }

  local required_dirs=(
    "notebooks"
    "datasets"
    "models"
    "logs"
    "visualizations"
    "scripts"
    "outputs/csv_logs"
    "outputs/gradcam_images"
  )

  local d
  for d in "${required_dirs[@]}"; do
    check_path "$d"
  done

  check_path "README_${tag_name}.md"
  check_path "__init__.py"
  check_path "scripts/__init__.py"

  check_path "scripts/py_build_model_${tag_name}.py"
  check_path "scripts/py_train_model_${tag_name}.py"
  check_path "scripts/py_inference_${tag_name}.py"
  check_path "scripts/py_utils_${tag_name}.py"

  check_path "notebooks/00_data_exploration_${tag_name}.ipynb"
  check_path "notebooks/01_model_build_${tag_name}.ipynb"
  check_path "notebooks/02_training_${tag_name}.ipynb"
  check_path "notebooks/03_inference_quick_explore_${tag_name}.ipynb"

  if [ "$missing" -eq 0 ]; then
    printf 'OK: scaffold complete at %s\n' "$tag_dir"
  fi

  return "$missing"
}

if [ "${1:-}" = "--check" ]; then
  if [ "$#" -ne 3 ]; then
    usage >&2
    exit 2
  fi

  check_scaffold "$2" "$3"
  exit $?
fi

if [ "$#" -lt 2 ]; then
  usage >&2
  exit 2
fi

ROOT_DIR=$1
shift

WITH_NB_STUBS="${WITH_NB_STUBS:-0}"

NB_FILES=(
  "00_data_exploration"
  "01_model_build"
  "02_training"
  "03_inference_quick_explore"
)

PY_FILES=(
  "py_build_model"
  "py_train_model"
  "py_inference"
  "py_utils"
)

DIRS=(
  "notebooks"
  "datasets"
  "models"
  "logs"
  "visualizations"
  "scripts"
  "outputs/csv_logs"
  "outputs/gradcam_images"
)

mkd "$ROOT_DIR"

for tag in "$@"; do
  TAG_DIR="${ROOT_DIR%/}/$tag"
  TAG_NAME="$(basename -- "$tag")"

  for d in "${DIRS[@]}"; do
    mkd "$TAG_DIR/$d"
  done

  touch_safe "$TAG_DIR/README_${TAG_NAME}.md"
  touch_safe "$TAG_DIR/__init__.py"
  touch_safe "$TAG_DIR/scripts/__init__.py"

  for stem in "${NB_FILES[@]}"; do
    dst="$TAG_DIR/notebooks/${stem}_${TAG_NAME}.ipynb"

    if [ ! -f "$dst" ]; then
      if [ "$WITH_NB_STUBS" = "1" ]; then
        emit_ipynb "$dst"
      else
        touch_safe "$dst"
      fi
    fi
  done

  for stem in "${PY_FILES[@]}"; do
    touch_safe "$TAG_DIR/scripts/${stem}_${TAG_NAME}.py"
  done

  printf 'OK: scaffold created or verified at %s\n' "$TAG_DIR"
done
