# Auto-generated by apply_local_fixes.sh
from pathlib import Path
import json, time

def log_test_summary(acc, loss, seed, tagdir):
    """Write test summary JSON to outputs/, returning the path."""
    ts = int(time.time())
    out = Path(tagdir) / "outputs" / f"test_summary_seed{int(seed)}_{ts}.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    with open(out, "w") as f:
        json.dump(
            {"acc": float(acc), "loss": float(loss), "seed": int(seed), "ts": ts},
            f,
        )
    return str(out)
